spring:
  application:
    name: civism-cloud-client
server:
  port: 8082

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30   # 失效时间，默认90s，如果服务在指定的 失效时间 内仍没有发起心跳请求，将会被剔除EurekaServer
    lease-renewal-interval-in-seconds: 10      # 心跳间隔（秒），默认30s
    prefer-ip-address: true                    # 实例名称显示IP配置（与instance-id配合使用）
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}  # 将InstanceID设置为 IP:Port 形式
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
